SET foreign_key_checks = 0;

DROP TABLE IF EXISTS dualex;
CREATE TABLE dualex(
	parametro VARCHAR(256) PRIMARY KEY,
	valor VARCHAR(256)
);
INSERT INTO dualex VALUES('versión', '0.1');

DROP TABLE IF EXISTS Usuario;
CREATE TABLE Usuario(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(256),
	apellidos VARCHAR(256),
	email VARCHAR(256) UNIQUE,
	clave VARCHAR(256)
);

DROP TABLE IF EXISTS Alumno;
CREATE TABLE Alumno(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	FOREIGN KEY (id) REFERENCES Usuario (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Profesor;
CREATE TABLE Profesor(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	FOREIGN KEY (id) REFERENCES Usuario (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Modulo;
CREATE TABLE Modulo(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	codigo VARCHAR(256),
	titulo VARCHAR(256),
	colorFondo VARCHAR(256) DEFAULT '#0000FF',
	colorLetra VARCHAR(256) DEFAULT '#FFFFFF',
	icono VARCHAR(256) DEFAULT 'default.svg'
);

